"""
Step 4b: Minimal FastAPI server — proves Twilio can reach OUR server
(via ngrok) and get back dynamically generated TwiML.

No WebSocket, no OpenAI yet — just a single HTTP route.

Run: uvicorn src.server:app --reload --port 8000
(then separately: ngrok http 8000)
"""
from fastapi import FastAPI, Response

app = FastAPI()


@app.get("/")
def health_check():
    """Simple route to confirm the server is up at all, via plain browser visit."""
    return {"status": "ok", "message": "Voice bot server is running"}


@app.post("/twiml")
def twiml_webhook():
    """
    Twilio will POST here when the call connects, expecting TwiML back.
    For now this just proves the round trip works — same static message
    as our first test, but now served dynamically from our own server.
    """
    twiml = """<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Say voice="Polly.Joanna">This message was generated by our own server, reached through ngrok. Goodbye.</Say>
</Response>"""
    return Response(content=twiml, media_type="application/xml")